### ISSUE TITLE
Fixing the memory leak problem

### ISSUE THREAD

**Issue by Weisstrieb** [caznova/TEXExtract#6]
1. Change every usage of MemoryStream with `using(MemoryStream ms)`
2. Dispose of every bitmap instance after save.
3. Call it in end of while loop of Form1.cs
```
GC.Collect();
GC.WaitForPendingFinalizers();
GC.Collect();
```

These will resolve the memory leak problem.

**Comment by BringerxD** [comment]
how to fix this problem?
